# Experiment Management Configuration
# -----------------------------------

experiment: 
  name: "Hybrid_SNN_Compression_Fraud_V1"
  seed: 42
  run_id: "auto" # Or provide a specific ID for the run (e.g., timestamp)
  log_level: "INFO" # Options: "DEBUG", "INFO", "WARNING", "ERROR"
  experiment_dir: "experiments/"
  dataset_name: "credit_card_fraud" # Options: credit_card_fraud & synthetic_data
  xai_cases : 25

tracker: 
  enabled: True
  type: "CodeCarbon" # Options: "wandb", "tensorboard", "
  project: 'Green-AI-Fraud-Detection'
  output_directory: 'experiments/'
  log_level: 'error'
