# Explainable AI (XAI) Configuration
# ----------------------------------

xai:
  top_k: 3 # Quantity of key features 
  num_features: 10 # To considering
  save_xai_cases: True # Save particular anlysis

lime:
  enabled: True
  sample_around_instance: True # Sample around the instance to explain
  kernel_width: 0.75

